version: '3.1'

services:

  test_task:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    command: >
     sh -c "cd TestTaskApi && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

networks:
  mynetwork:
    driver: bridge